[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"

[browser]
gatherUsageStats = false
[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1e88e5"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans serif"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = false

[runner]
magicEnabled = false

[mapbox]
token = ""
