[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"

[browser]
gatherUsageStats = false